package com.example.travelpoint;

import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.AppCompatButton;

import android.os.Bundle;
import android.view.View;
import android.widget.TextView;

public class e_privacy_policy extends AppCompatActivity {

    AppCompatButton btn_back;
    TextView pp_des;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.e_privacy_policy_main);

        btn_back = findViewById(R.id.btn_back_pri);
        pp_des = findViewById(R.id.pp_des);

        btn_back.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                onBackPressed();
            }
        });

        pp_des.setText("Last updated: January 17, 2021\n" +
                "\n" +
                "This Privacy Policy describes Our policies and procedures on the collection,\n" +
                "use and disclosure of Your information when You use the Service and tells You\n" +
                "about Your privacy rights and how the law protects You.\n" +
                "\n" +
                "We use Your Personal data to provide and improve the Service. By using the\n" +
                "Service, You agree to the collection and use of information in accordance with\n" +
                "this Privacy Policy. This Privacy Policy has been created with the help of the\n" +
                "[Privacy Policy Generator](https://www.privacypolicies.com/privacy-policy-\n" +
                "generator/).\n" +
                "\n" +
                "Interpretation and Definitions  \n" +
                "==============================\n" +
                "\n" +
                "Interpretation  \n" +
                "--------------\n" +
                "\n" +
                "The words of which the initial letter is capitalized have meanings defined\n" +
                "under the following conditions. The following definitions shall have the same\n" +
                "meaning regardless of whether they appear in singular or in plural.\n" +
                "\n" +
                "Definitions  \n" +
                "-----------\n" +
                "\n" +
                "For the purposes of this Privacy Policy:\n" +
                "\n" +
                "  * Account means a unique account created for You to access our Service or\n" +
                "    parts of our Service.\n" +
                "\n" +
                "  * Affiliate means an entity that controls, is controlled by or is under\n" +
                "    common control with a party, where \"control\" means ownership of 50% or\n" +
                "    more of the shares, equity interest or other securities entitled to vote\n" +
                "    for election of directors or other managing authority.\n" +
                "\n" +
                "  * Application means the software program provided by the Company downloaded\n" +
                "    by You on any electronic device, named TravalPoint\n" +
                "\n" +
                "  * Company (referred to as either \"the Company\", \"We\", \"Us\" or \"Our\" in this\n" +
                "    Agreement) refers to TravalPoint.\n" +
                "\n" +
                "  * Country refers to: Malaysia\n" +
                "\n" +
                "  * Device means any device that can access the Service such as a computer, a\n" +
                "    cellphone or a digital tablet.\n" +
                "\n" +
                "  * Personal Data is any information that relates to an identified or\n" +
                "    identifiable individual.\n" +
                "\n" +
                "  * Service refers to the Application.\n" +
                "\n" +
                "  * Service Provider means any natural or legal person who processes the data\n" +
                "    on behalf of the Company. It refers to third-party companies or\n" +
                "    individuals employed by the Company to facilitate the Service, to provide\n" +
                "    the Service on behalf of the Company, to perform services related to the\n" +
                "    Service or to assist the Company in analyzing how the Service is used.\n" +
                "\n" +
                "  * Third-party Social Media Service refers to any website or any social\n" +
                "    network website through which a User can log in or create an account to\n" +
                "    use the Service.\n" +
                "\n" +
                "  * Usage Data refers to data collected automatically, either generated by the\n" +
                "    use of the Service or from the Service infrastructure itself (for example,\n" +
                "    the duration of a page visit).\n" +
                "\n" +
                "  * You means the individual accessing or using the Service, or the company,\n" +
                "    or other legal entity on behalf of which such individual is accessing or\n" +
                "    using the Service, as applicable.\n" +
                "\n" +
                "\n" +
                "Contact Us  \n" +
                "==========\n" +
                "\n" +
                "If you have any questions about this Privacy Policy, You can contact us:\n" +
                "\n" +
                "  * By email: swe1804433@xmu.edu.my");
    }

}